services:
  - type: web
    name: delta-trading-bot
    env: python
    # This build command is for Render's Python buildpack
    buildCommand: pip install -r requirements.txt
    # This is your specified start command
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --preload app:app
    healthCheckPath: /health
    disk: # Define a persistent disk for your SQLite database
      name: trading-bot-data
      mountPath: /var/data
      sizeGB: 1 # You can adjust the size as needed, 1GB is usually plenty for SQLite
    envVars:
      - key: DELTA_API_KEY
        sync: false # Set this value in Render dashboard for security
      - key: DELTA_API_SECRET
        sync: false # Set this value in Render dashboard for security
      - key: MAX_POSITION_SIZE
        value: "10"
      - key: MAX_DAILY_LOSS
        value: "1000.0"
      - key: RISK_MANAGEMENT_ENABLED
        value: "true"
      - key: DATABASE_PATH
        value: "/var/data/trading_system.db" # Mount path of your persistent disk
    # plan: free # or starter, pro, etc.
    # numInstances: 1 # Number of instances
